name: Build Android 13 - 5.10

on:
  workflow_call:
    inputs:
      ksu_commit:
        type: string
        required: false
        default: ''
      feature_set:
        type: string
        required: false
        default: 'WKSU+SUSFS+BBG'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Android 13 - 5.10"
    strategy:
      fail-fast: false
      matrix:
        kernel_version:
          - "5.10.107-android13-2022-04"
          - "5.10.107-android13-2022-05"
          - "5.10.107-android13-2022-06"
          - "5.10.107-android13-2022-07"
          - "5.10.107-android13-2022-08"
          - "5.10.107-android13-2022-09"
          - "5.10.107-android13-2022-10"
          - "5.10.107-android13-2022-11"
          - "5.10.149-android13-2022-12"
          - "5.10.149-android13-2023-01"
          - "5.10.157-android13-2023-02"
          - "5.10.157-android13-2023-03"
          - "5.10.168-android13-2023-04"
          - "5.10.168-android13-2023-05"
          - "5.10.177-android13-2023-06"
          - "5.10.177-android13-2023-07"
          - "5.10.186-android13-2023-08"
          - "5.10.186-android13-2023-09"
          - "5.10.189-android13-2023-10"
          - "5.10.189-android13-2023-11"
          - "5.10.198-android13-2023-12"
          - "5.10.198-android13-2024-01"
          - "5.10.205-android13-2024-02"
          - "5.10.205-android13-2024-03"
          - "5.10.209-android13-2024-04"
          - "5.10.209-android13-2024-05"
          - "5.10.210-android13-2024-06"
          - "5.10.214-android13-2024-07"
          - "5.10.218-android13-2024-08"
          - "5.10.223-android13-2024-09"
          - "5.10.223-android13-2024-11"
          - "5.10.228-android13-2025-01"
          - "5.10.234-android13-2025-03"
          - "5.10.236-android13-2025-05"
          - "5.10.238-android13-2025-07"
          - "5.10.243-android13-2025-10"
          - "5.10.246-android13-2026-01"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      kernel_version: ${{ matrix.kernel_version }}
      ksu_commit: ${{ inputs.ksu_commit }}
      feature_set: ${{ inputs.feature_set }}
