name: Build Android 13 - 5.15

on:
  workflow_call:
    inputs:
      ksu_commit:
        type: string
        required: false
        default: ''
      feature_set:
        type: string
        required: false
        default: 'WKSU+SUSFS+BBG'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kernel_version:
          - "5.15.41-android13-2022-06"
          - "5.15.41-android13-2022-07"
          - "5.15.41-android13-2022-08"
          - "5.15.41-android13-2022-09"
          - "5.15.41-android13-2022-10"
          - "5.15.41-android13-2022-11"
          - "5.15.74-android13-2022-12"
          - "5.15.74-android13-2023-01"
          - "5.15.78-android13-2023-02"
          - "5.15.78-android13-2023-03"
          - "5.15.94-android13-2023-04"
          - "5.15.94-android13-2023-05"
          - "5.15.104-android13-2023-06"
          - "5.15.104-android13-2023-07"
          - "5.15.119-android13-2023-08"
          - "5.15.119-android13-2023-09"
          - "5.15.123-android13-2023-10"
          - "5.15.123-android13-2023-11"
          - "5.15.137-android13-2023-12"
          - "5.15.137-android13-2024-01"
          - "5.15.144-android13-2024-02"
          - "5.15.144-android13-2024-03"
          - "5.15.148-android13-2024-04"
          - "5.15.148-android13-2024-05"
          - "5.15.149-android13-2024-06"
          - "5.15.149-android13-2024-07"
          - "5.15.151-android13-2024-08"
          - "5.15.153-android13-2024-09"
          - "5.15.167-android13-2024-11"
          - "5.15.170-android13-2025-01"
          - "5.15.178-android13-2025-03"
          - "5.15.180-android13-2025-05"
          - "5.15.185-android13-2025-07"
          - "5.15.189-android13-2025-09"
          - "5.15.194-android13-2025-12"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      kernel_version: ${{ matrix.kernel_version }}
      ksu_commit: ${{ inputs.ksu_commit }}
      feature_set: ${{ inputs.feature_set }}
