name: Build Bypass Kernels

on:
  workflow_call:
    inputs:
      ksu_commit:
        type: string
        required: false
        default: ''
      feature_set:
        type: string
        required: false
        default: 'WKSU+SUSFS+BBG'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kernel_version:
          - "5.10.X-android12-lts"
          - "5.10.X-android13-lts"
          - "5.15.X-android13-lts"
          - "5.15.X-android14-lts"
          - "6.1.X-android14-lts"
          - "6.6.X-android15-lts"
          - "6.12.X-android16-lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      kernel_version: ${{ matrix.kernel_version }}
      ksu_commit: ${{ inputs.ksu_commit }}
      feature_set: ${{ inputs.feature_set }}
