name: Kernel Config - A12 5.10

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_commit:
        required: false
        type: string
      feature_set:
        required: true
        type: string
      build_bypass:
        required: true
        type: boolean
      add_nomount:
        required: false
        type: boolean
        default: false
      add_nomountX:
        required: false
        type: boolean
        default: false
      add_hymofs:
        required: false
        type: boolean
        default: false

jobs:
  build-kernels-a12:
    name: "5.10.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 12 - 5.10)
        # Active series
        - sub_level: "236"
          os_patch_level: "2025-05"
        #- sub_level: "246"
        #  os_patch_level: "2025-12"
        #- sub_level: "250"
        #  os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_commit: ${{ inputs.ksu_commit }}
      feature_set: ${{ inputs.feature_set }}
      build_bypass: ${{ inputs.build_bypass }}
      add_nomount: ${{ inputs.add_nomount }}
      add_nomountX: ${{ inputs.add_nomountX }}
      add_hymofs: ${{ inputs.add_hymofs }}
